# Generated by Django 6.0.3 on 2026-03-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Setter', 'Setter'), ('Libero', 'Libero'), ('Middle Blocker', 'Middle Blocker'), ('Outside Hitter', 'Outside Hitter'), ('Opposite', 'Opposite')], max_length=50),
        ),
    ]
